# -*- coding: UTF-8 -*- 

"""
Django settings for archer project.

Generated by 'django-admin startproject' using Django 1.8.17.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os


BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'hfusaf2m4ot#7)fkw#di2bu6(cv0@opwmafx5n#6=3d%x^hpl6'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = (

)

MIDDLEWARE_CLASSES = (
     'django.contrib.sessions.middleware.SessionMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
)


ROOT_URLCONF = 'dongjsPy.urls'


#WSGI_APPLICATION = 'archer.wsgi.application'

# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = False



#inception缂佸嫪娆㈤幍锟介崷銊ф畱閸︽澘娼�
#online濮濓絽绱￠悳顖氼暔
#10.10.10.36 3310
#缁惧じ绗傞悳顖氼暔
INCEPTION_HOST = '192.168.131.128'
INCEPTION_PORT = '6668'

#閺堫剙婀撮悳顖氼暔
#127.0.0.1 6669
#dev濞村鐦悳顖氼暔
#192.168.11.75 6669
#缁惧じ绗傚ù瀣槸閻滎垰顣�
#online濞村鐦悳顖氼暔
#172.24.32.28 3320
TEST_INCEPTION_HOST = '192.168.131.128'
TEST_INCEPTION_PORT = '6668'

#閺屻儳婀呴崶鐐寸泊SQL閺冭泛锟芥瑤绱伴悽銊ュ煂閿涘矁绻栭柌宀冾洣閸涘﹨鐦攁rcher閸樿鎽㈡稉鐚皔sql闁插矁顕伴崣鏉媙ception婢跺洣鍞ら惃鍕礀濠婃矮淇婇幁顖氭嫲SQL.
#濞夈劍鍓版潻娆撳櫡鐟曚礁鎷癷nception缂佸嫪娆㈤惃鍒琻ception.conf闁插瞼娈慽nception_remote_XX闁劌鍨庢穱婵囧瘮娑擄拷閼凤拷.
INCEPTION_REMOTE_BACKUP_HOST='127.0.0.1'
INCEPTION_REMOTE_BACKUP_PORT=3306
INCEPTION_REMOTE_BACKUP_USER='root'
INCEPTION_REMOTE_BACKUP_PASSWORD='1212ming'

